export const COMPANY_DATA = [
    { name: "Google", role: "SDE-1", desc: "Data Structures, Algorithms, System Design, Graph Theory" },
    { name: "Amazon", role: "SDE-1", desc: "Leadership Principles, Data Structures, Problem Solving" },
    { name: "TCS NQT", role: "System Engineer", desc: "Aptitude, Core CS subjects, Basic Coding, OOPS" },
    { name: "Microsoft", role: "Software Engineer", desc: "Data Structures, Sorting algorithms, String manipulation, CS Fundamentals" },
    { name: "Reliance Industries", role: "Graduate Engineer Trainee", desc: "Core Engineering, Problem Solving, Aptitude, Technical domain knowledge" },
    { name: "HDFC Bank", role: "IT Officer", desc: "Database Management, Networking, Banking software operations, Information Security" },
    { name: "Bharti Airtel", role: "Network Engineer", desc: "Telecom networking, IP routing, Unix/Linux, Scripting" },
    { name: "SBI", role: "Probationary Officer (IT)", desc: "Quantitative Aptitude, General Awareness, Basic IT fundamentals, Reasoning" },
    { name: "ICICI Bank", role: "IT Application Manager", desc: "Java/J2EE, Database tuning, API integration, BFSI concepts" },
    { name: "TCS", role: "System Engineer", desc: "Core CS, Java/Python, RDBMS, Software Engineering concepts" },
    { name: "Bajaj Finance", role: "Software Developer", desc: "React, Node.js, Microservices, Cloud Basics" },
    { name: "Larsen & Toubro", role: "Software Engineer", desc: "C/C++, Embedded Systems, IoT concepts, Basic DSA" },
    { name: "Infosys", role: "System Engineer Trainee", desc: "Object Oriented Programming, Database concepts, Logical reasoning, SQL" },
    { name: "Life Insurance Corp", role: "Assistant Administrative Officer (IT)", desc: "Aptitude, Core IT knowledge, Database, Security" },
    { name: "Hind. Unilever", role: "IT Business Analyst", desc: "Data Analytics, requirement gathering, Agile, Supply Chain IT" },
    { name: "Maruti Suzuki", role: "IT Graduate Trainee", desc: "ERP systems, Database, basic Python/SQL for data" },
    { name: "Axis Bank", role: "IT Officer", desc: "Banking IT infrastructure, Finacle basics, SQL, Networking" },
    { name: "Sun Pharma", role: "IT Support Engineer", desc: "Network support, ITIL frameworks, Database maintenance" },
    { name: "Titan Company", role: "Data Analyst", desc: "SQL, Python, Excel, PowerBI/Tableau" },
    { name: "M & M", role: "Software Trainee", desc: "Automotive IT, IoT software, basic cloud concepts" },
    { name: "HCL Technologies", role: "Software Engineer", desc: "Java, Spring Boot, Application Support, Testing" },
    { name: "ITC", role: "IT Manager Trainee", desc: "Supply chain systems, ERP SAP, Project management basics" },
    { name: "Adani Power", role: "IT Trainee", desc: "SCADA systems, Industrial networking, Database basics" },
    { name: "NTPC", role: "Executive Trainee (IT)", desc: "Core CS, Networks, Database, Operating Systems" },
    { name: "Kotak Mah. Bank", role: "IT System Analyst", desc: "SQL, BFSI IT, API lifecycle" },
    { name: "Adani Ports", role: "IT Engineer", desc: "Logistics software, DB management, Networking" },
    { name: "ONGC", role: "Programming Officer", desc: "C/C++, DBMS, Software engineering" },
    { name: "UltraTech Cem.", role: "IT Executive", desc: "SAP basics, IT operations, network fundamentals" },
    { name: "Bharat Electron", role: "Probationary Engineer", desc: "Electronics, Embedded C, RTOS, Signals" }
];
